#ifndef GLOBALS_H
#define GLOBALS_H

#define REQUEST_SOURCE_CHANGE_TO_CD 0
#define REQUEST_SOURCE_CHANGE_TO_TUNER 1
#define REQUEST_SOURCE_CHANGE_TO_USB 2
#define REQUEST_SOURCE_CHANGE_TO_SERVER 3
#define REQUEST_SOURCE_CHANGE_TO_NETRADIO 4
#define REQUEST_SOURCE_CHANGE_TO_SPOTIFY 5
#define REQUEST_SOURCE_CHANGE_TO_AIRPLAY 6
#define REQUEST_SOURCE_CHANGE_TO_AUX1 7
#define REQUEST_SOURCE_CHANGE_TO_AUX2 8
#define REQUEST_SOURCE_CHANGE_TO_DIGITAL1 9
#define REQUEST_SOURCE_CHANGE_TO_DIGITAL2 10

#define REQUEST_POWER_TOGGLE 11
#define REQUEST_MUTE_TOGGLE 12

typedef enum {
    Request = 0,
    QueryData,
}

#endif
